@startuml test

!define RECTANGLE class
!define INTERFACE interface

RECTANGLE AzureResourceManager {
  + Resource Groups
  + Resources
}

RECTANGLE VirtualNetwork {
  + Subnets
  + NSGs
}

RECTANGLE WebApp {
  + App Service Plan
  + App Service
  + Database
}

INTERFACE User {
  + Browser
}

User --> WebApp
WebApp --> VirtualNetwork
VirtualNetwork --> AzureResourceManager

@enduml
